[Service]
Host = "labsair-device-vehicle-simulator"
Port = 48992
ConnectRetries = 3
Labels = []
OpenMsg = "device vehicle started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "/custom-config"

[Logging]
EnableRemote = true
File = "./device-vehicle.log"

[Writable]
LogLevel = "INFO"

# Pre-define Devices
[[DeviceList]]
  Name = "train-0001"
  Profile = "Vehicle-Device"
  Description = "Vehicle device simulator"
  Labels = [ "train", "cargo" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "devicevehicle"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "5s"
    OnChange = false
    Resource = "GPS"
  [[DeviceList.AutoEvents]]
    Frequency = "8s"
    OnChange = false
    Resource = "Speedometer"

[[DeviceList]]
  Name = "train-0002"
  Profile = "Vehicle-Device"
  Description = "Vehicle device simulator"
  Labels = [ "train", "cargo" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "devicevehicle"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "5s"
    OnChange = false
    Resource = "GPS"
  [[DeviceList.AutoEvents]]
    Frequency = "8s"
    OnChange = false
    Resource = "Speedometer"

[[DeviceList]]
  Name = "train-0003"
  Profile = "Vehicle-Device"
  Description = "Vehicle device simulator"
  Labels = [ "train", "cargo" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "devicevehicle"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "5s"
    OnChange = false
    Resource = "GPS"
  [[DeviceList.AutoEvents]]
    Frequency = "8s"
    OnChange = false
    Resource = "Speedometer"
