[Service]
Host = "host.docker.internal"
Port = 48995
ConnectRetries = 20
Labels = []
OpenMsg = "device Siemens started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "localhost"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "localhost"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
EnableRemote = false
File = "./device-siemens.log"
Level = "DEBUG"

[Writable]
LogLevel = 'INFO'

# Pre-define Devices
[[DeviceList]]
  Name = "versicharge-0001"
  Profile = "Siemens-SimDevice"
  Description = "Siemens VersiCharge device simulator"
  Labels = [ "charger", "ev" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = "devicesiemens"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Frequency = "5s"
    OnChange = false
    Resource = "Status"
  [[DeviceList.AutoEvents]]
    Frequency = "5s"
    OnChange = false
    Resource = "Voltage"
  [[DeviceList.AutoEvents]]
    Frequency = "5s"
    OnChange = false
    Resource = "Current"

